---
title: "CESAM_MS"
author: "Juliette Champagnat"
date: "2024-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# rm(list=ls())
## devtools::install_github("James-Thorson-NOAA/dsem")
## install.packages("dsem")
library(TMB)
library(dsem)
library(ggplot2)
library(dplyr)
## devtools::install_github("afsc-assessments/GOApollock", ref='dev')
# devtools::install_github("jchampag/GOApollock", ref='dev')
library(GOApollock)
library(readxl)
# theme_set(theme_bw())
library(phylopath)
library(ggpubr)
library(reshape)
library(gridExtra)
source("AssessDsem_fns.R")
```


# Data 

```{r}
## Load ESP data
ESPdata <- read.csv('GitHub/GOApollock/Data/2023/ESP_2024_4SCEAM.csv')

## set number of years for projection
ny_proj = 5

## get them ready
ESPdata_MS  <- ESPdata %>% 
  # adding NA before (match assessment begining) 
  bind_rows(data.frame(Year=c(1970:1976))) %>% arrange(Year) %>% 
  #  sdding NA after (forecast)
  add_row(Sum_OffYOY_Shelikof=rep(NA,ny_proj)) %>% 
  # selecting time series of interest
  select(Spr_SST,Wind_NS,Sum_LCopepod_Shelikof,Sum_Euph_Kodiak,
         Spr_Larvae_Shelikof,Sum_OffYOY_Shelikof,Sum_NearYOY_Kodiak,
         Sum_OffYOY_Cond_Shelikof,
         Sum_Juv_EuphDiet,Fal_Adult_Cond_Fishery) %>% 
  #scale and log data
  mutate(across(.cols=c(Spr_Larvae_Shelikof,Sum_OffYOY_Shelikof,Sum_NearYOY_Kodiak),.fns=log)) %>% 
  mutate(across(.fns =scale,.cols=-c(Spr_Larvae_Shelikof,Sum_OffYOY_Shelikof,Sum_NearYOY_Kodiak))) 
    
View(ESPdata_MS)  

```

# Model runs

## iid

```{r}

sem_MS_iid = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs <-> recdevs, 0, sigmaR, 1
"

fit_assess_dsem_MS_iid <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_iid' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_iid,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)
fit_assess_dsem_MS_iid$opt$AIC

fit_assess_dsem_MS_MapMod$opt$AIC

retrAD_real_MS_iid <- retro_proj_analysis_AssessDsem(sem=sem_MS_iid,
                            fit=fit_assess_dsem_MS_iid,
                            peels=0:2,env_data = 'real',ny_proj = 3)




```

## AR1

```{r}

# fit_assess_dsem_DAG8_2SST_darrow_RAR1


sem_MS_AR1 = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs -> recdevs, 1, AR_R, 1
"

fit_assess_dsem_MS_AR1 <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_AR1' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_AR1,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)


```



## Regression

```{r}

# names(ESPdata_MS)

sem_MS_regWind = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs <-> recdevs, 0, sigmaR, 1

  #causal relation
  Wind_NS -> recdevs,1,Wind_to_R
  "

fit_assess_dsem_MS_regwind <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_regWind' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_regWind,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)


retrAD_real_MS_regWind <- retro_proj_analysis_AssessDsem(sem=sem_MS_regWind,
                            fit=fit_assess_dsem_MS_regwind,
                            peels=0:2,env_data = 'real',ny_proj = 3)


``` 


## Map simple 

```{r}
sem_MS_MapSpl = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs <-> recdevs, 0, sigmaR, 1

  #causal relation
  #Sum_Euph_Kodiak -> Fal_Adult_Cond_Fishery, 0, Euph_to_CondAd 
  #Fal_Adult_Cond_Fishery -> Spr_Larvae_Shelikof,1,CondAd_to_Larvae
  Spr_SST -> Spr_Larvae_Shelikof,0,SST_to_Larvae
  Wind_NS -> Spr_Larvae_Shelikof,0,Wind_to_Larvae
  Spr_Larvae_Shelikof -> Sum_OffYOY_Shelikof,0,Larvae_to_OffYOY
  #Spr_Larvae_Shelikof -> Sum_NearYOY_Kodiak,0,Larvae_to_NearYOY
  Sum_OffYOY_Shelikof -> recdevs, 1, offYOY_to_R
  #Sum_NearYOY_Kodiak -> recdevs, 1,nearYOY_to_R#,1
  #Sum_LCopepod_Shelikof -> Sum_OffYOY_Cond_Shelikof,0,Cope_to_CondYOY
  #Sum_Juv_EuphDiet -> Sum_OffYOY_Cond_Shelikof,0,JuvEuphDiet_to_CondYOY
  Sum_OffYOY_Cond_Shelikof -> recdevs,1,CondYOY_to_R
  "

fit_assess_dsem_MS_MapSpl <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_MapSpl' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_MapSpl,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)

retrAD_real_MS_MapSpl <- retro_proj_analysis_AssessDsem(sem=sem_MS_MapSpl,
                            fit=fit_assess_dsem_MS_MapSpl,
                            peels=0:1,env_data = 'real',ny_proj = 3)



causal_plot(fits = list(fit_assess_dsem_MS_MapSpl))
rec_plot(fits = list(fit_assess_dsem_MS_MapSpl,fit_assess_dsem_DAG8simple),points=T)

fit_assess_dsem_DAG8simple$sem_full %>% dim()
fit_assess_dsem_MS_MapSpl$sem_full %>% dim()
```

## Map moderate

```{r}

# names(ESPdata_MS)
sem_MS_MapMod = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs <-> recdevs, 0, sigmaR, 1

  #causal relation
  Sum_Euph_Kodiak -> Fal_Adult_Cond_Fishery, 0, Euph_to_CondAd 
  Fal_Adult_Cond_Fishery -> Spr_Larvae_Shelikof,1,CondAd_to_Larvae
  #Spr_SST -> Spr_Larvae_Shelikof,0,SST_to_Larvae
  Wind_NS -> Spr_Larvae_Shelikof,0,Wind_to_Larvae
  Spr_Larvae_Shelikof -> Sum_OffYOY_Shelikof,0,Larvae_to_OffYOY
  Sum_OffYOY_Shelikof <-> Sum_NearYOY_Kodiak,0,OffYOY_to_NearYOY
  #Spr_SST -> Sum_OffYOY_Shelikof,0, SST_to_OffYOY
  Sum_OffYOY_Shelikof -> recdevs, 1, offYOY_to_R
  Spr_SST -> recdevs, 1,SST_to_R
  Spr_SST -> Sum_OffYOY_Cond_Shelikof,0,SST_to_CondYOY
  Sum_OffYOY_Cond_Shelikof -> recdevs,1,CondYOY_to_R
  "

fit_assess_dsem_MS_MapMod <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_MapMod' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_MapMod,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)


retrAD_real_MS_MapMod <- retro_proj_analysis_AssessDsem(sem=sem_MS_MapMod,
                            fit=fit_assess_dsem_MS_MapMod,
                            peels=0:10,env_data = 'real',ny_proj = 5)


retrAD_real_MS_MapMod %>% length()
skillpred_real_MS_MapMod <- unlist(retrAD_real_MS_MapMod,recursive = FALSE)
length(skillpred_real_MS_MapMod)
save(skillpred_real_MS_MapMod,file='skilltest_real_MS_MapMod.Rdata')
```

## Map complex

```{r}

sem_MS_MapCpl = "
  # link, lag, param_name, start_value

  #internal data relation
  Spr_SST -> Spr_SST,1,AR_SST
  Wind_NS -> Wind_NS,1,AR_Wind
  Sum_LCopepod_Shelikof -> Sum_LCopepod_Shelikof,1, AR_Cope
  Sum_Euph_Kodiak -> Sum_Euph_Kodiak,1,AR_Euph
  Spr_Larvae_Shelikof - > Spr_Larvae_Shelikof,1,AR_larvae
  Sum_OffYOY_Cond_Shelikof -> Sum_OffYOY_Cond_Shelikof,1,AR_CondOffYOY
  Sum_OffYOY_Shelikof -> Sum_OffYOY_Shelikof,1,AR_OffYOY
  Sum_NearYOY_Kodiak -> Sum_NearYOY_Kodiak,1,AR_NearYOY
  Sum_Juv_EuphDiet -> Sum_Juv_EuphDiet,1,AR_JuvEuphDiet
  Fal_Adult_Cond_Fishery -> Fal_Adult_Cond_Fishery,1,AR_CondAd
  recdevs <-> recdevs, 0, sigmaR, 1

  #causal relation
  Sum_Euph_Kodiak -> Fal_Adult_Cond_Fishery, 0, Euph_to_CondAd 
  Fal_Adult_Cond_Fishery -> Spr_Larvae_Shelikof,1,CondAd_to_Larvae
  Spr_SST -> Spr_Larvae_Shelikof,0,SST_to_Larvae
  Wind_NS -> Spr_Larvae_Shelikof,0,Wind_to_Larvae
  Spr_Larvae_Shelikof -> Sum_OffYOY_Shelikof,0,Larvae_to_OffYOY
  Spr_Larvae_Shelikof -> Sum_NearYOY_Kodiak,0,Larvae_to_NearYOY
  Sum_OffYOY_Shelikof -> recdevs, 1, offYOY_to_R
  Sum_NearYOY_Kodiak -> recdevs, 1,nearYOY_to_R#,1
  Sum_LCopepod_Shelikof -> Sum_OffYOY_Cond_Shelikof,0,Cope_to_CondYOY
  Sum_Juv_EuphDiet -> Sum_OffYOY_Cond_Shelikof,0,JuvEuphDiet_to_CondYOY
  Sum_OffYOY_Cond_Shelikof -> recdevs,1,CondYOY_to_R
  "


fit_assess_dsem_MS_MapCpl <- AssessDsem_fit(fit_type = "AssessDsem",
                             fit_name = '_MS_MapComplex' ,
                             ESPdata=ESPdata_MS,
                             sem=sem_MS_MapCpl,
                             sem_family =  rep('normal', ncol(ESPdata_MS)+1),
                             family_sd = rep(0.1, ncol(ESPdata_MS)+1),
                             ny_proj=ny_proj,
                             Assess_recdevs= NULL,
                             save_fit = FALSE,
                             save.sdrep=TRUE)


retrAD_real_MS_MapCpl <- retro_proj_analysis_AssessDsem(sem=sem_MS_MapCpl,
                            fit=fit_assess_dsem_MS_MapCpl,
                            peels=0:10,env_data = 'real',ny_proj = 5)


retrAD_real_MS_MapCpl %>% length()
skillpred_real_MS_MapCpl <- unlist(retrAD_real_MS_MapCpl,recursive = FALSE)
length(skillpred_real_MS_MapCpl)
save(skillpred_real_MS_MapCpl,file='skilltest_real_MS_MapCpl.Rdata')
```


# Manuscript figures/tables



## 1. Data bubble

```{r}

# Shelikof = Shelikof Strait pre-spawning winter acoustic survey
# Summer AT = Coastwide summer acoustic survey
# NMFS BT = Coastwide summer bottom trawl
# ADF&G BT = Near-shore summer bottom trawl

png(filename = '../plots/Fig2-data-overview.png',  units="in", width=8, height=5,res=300)
# tiff(filename='../plots/Fig2-data-overview.tiff', units="in", width=8, height=5, res=300)

 dd <- input_assess$dat
  x1 <- with(dd, data.frame(year=styr:endyr, size=cattot, survey='fishery', type='catch'))
  x2 <- with(dd, data.frame(year=fshyrs, size=multN_fsh, survey='fishery', type='ages'))
  x3 <- with(dd, data.frame(year=srvyrs1, size=indxsurv_log_sd1, survey='Shelikof', type='age 3+ index'))
  x4 <- with(dd, data.frame(year=srv_acyrs1, size=multN_srv1, survey='Shelikof', type='ages'))
  x5 <- with(dd, data.frame(year=srvyrs2, size=indxsurv_log_sd2, survey='NMFS BT', type='index'))
  x6 <- with(dd, data.frame(year=srv_acyrs2, size=multN_srv2, survey='NMFS BT', type='ages'))
  x7 <- with(dd, data.frame(year=srvyrs3, size=indxsurv_log_sd3, survey='ADF&G', type='index'))
  x8 <- with(dd, data.frame(year=srv_acyrs3, size=multN_srv3, survey='ADF&G', type='ages'))
  x9 <- with(dd, data.frame(year=srvyrs4, size=indxsurv_log_sd4, survey='Shelikof', type='age 1 index'))
  x10 <- with(dd, data.frame(year=srvyrs5, size=indxsurv_log_sd5, survey='Shelikof', type='age 2 index'))
  x11 <- with(dd, data.frame(year=srvyrs6, size=indxsurv_log_sd6, survey='Summer AT', type='index'))
  x12 <- with(dd, data.frame(year=srv_acyrs6, size=multN_srv6, survey='Summer AT', type='ages'))
  ## lengths special cases
  x13 <- with(dd, data.frame(year=srv_lenyrs2, size=multNlen_srv2, survey='NMFS BT', type='lengths'))
  x14 <- with(dd, data.frame(year=srv_lenyrs6, size=multNlen_srv6, survey='Summer AT', type='lengths'))

  ###ESP time series
  x15 <- ESPdata_MS %>%  #dat1[c(1,var_of_interest8)]
    mutate(year=dd$styr:(dd$styr+nrow(ESPdata_MS)-1),survey='Ecosystem and Socioeconomic Profile')%>% 
    pivot_longer(cols=-c(year,survey),values_to = 'size',names_to = 'type') %>%#names()
    filter(!is.na(size)) %>% mutate(size=0.1)


  ##
  dat <- rbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15)#x8,x9
  dat <- group_by(dat, survey, type) %>% mutate(relsize=size/max(size)) %>% ungroup
  dat <- mutate(dat, id=paste(survey, type, sep='_'))
  
  mycircles <- function(survey, type,y, color, lab=type){
    text(x=dd$endyr+2, y=ymax-y, label=lab, pos=4)
    xx <- dat[dat$survey==survey &  dat$type==type & dat$size>0,]
    if(nrow(xx)>0){
      symbols(x=xx$year, y=rep(ymax-y, length(xx$year)), circles=sqrt(xx$relsize),
              bg = adjustcolor(color, alpha.f=.6),
              add = TRUE, inches = .07)
    }
  }
  
  ## png('data.png', width=7, height=5, units='in', res=400)
  size.cex <- 1
  maxsize <- 2
  ymax <- 25
  xmid <- mean(unique(dat$year))
  par(mar=c(1.75,.75,.75,.75), mgp=c(1.5,.35,0), tck=-.01)
  plot(0, xlim = c(min(dat$year), dd$endyr+43), ylim = c(-1, ymax+1), axes = FALSE,  yaxs = "i",
       type = "n", xlab = NA, ylab = "" )
  box()
  
  cols <- c(rgb(127,201,127,max=256),rgb(190,174,212,max=256),rgb(253,192,134,max=256),rgb(255,255,153,max=256),
            rgb(56,108,176, max=256),rgb(56,128,106, max=256))
  text(x=xmid, y=ymax-.05, labels='Stock assessment data', font=2, cex=1.1)
  mycircles(survey='fishery', type='catch', y=1, color=cols[1], lab='Fishey catch')
  mycircles(survey='fishery', type='ages', y=2, color=cols[1], lab='Fishery age comps')
  mycircles(survey='Shelikof', type='ages', y=3, color=cols[2], 
            lab='Winter acoustic survey age comps')
  mycircles(survey='Shelikof', type='age 3+ index', y=4, color=cols[2], 
            lab='Winter acoustic survey age 3+ index')
  mycircles(survey='Summer AT', type='index', y=5, color=cols[3], 
            lab='Summer acoustic survey index')
  mycircles(survey='Summer AT', type='ages', y=6, color=cols[3], 
            lab='Summer acoustic survey age comps')
  mycircles(survey='Summer AT', type='lengths', y=7, color=cols[3], 
            lab='Summer acoustic survey length comps')
  mycircles(survey='NMFS BT', type='index', y=8, color=cols[4], 
            lab='Coastwide summer bottom trawl index')
  mycircles(survey='NMFS BT', type='ages', y=9, color=cols[4], 
            lab='Coastwide summer bottom trawl age comps')
  mycircles(survey='NMFS BT', type='lengths', y=10, color=cols[4], 
            lab='Coastwide summer bottom trawl length comps')
  mycircles(survey='ADF&G', type='index', y=11, color=cols[5], 
            lab='Nearshore summer bottom trawl index')
  mycircles(survey='ADF&G', type='ages', y=12, color=cols[5], 
            lab='Nearshore summer bottom trawl age comps')
  ### add ESP to the plot
 text(x=xmid, y=ymax-14.05, labels='Ecosystem and Socioeconomic Profile', font=2, cex=1.1)
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Spr_SST', y=15, color=cols[6], lab='Spring SST')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Wind_NS', y=16, color=cols[6], lab='Spring wind direction')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_Euph_Kodiak', y=17, color=cols[6], lab='Summer euphausiid')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Fal_Adult_Cond_Fishery', y=18, color=cols[6], lab='Fall adult condition')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Spr_Larvae_Shelikof', y=19, color=cols[6], lab='Spring larvae')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_NearYOY_Kodiak', y=20, color=cols[6], lab='Summer nearshore YOY')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_OffYOY_Shelikof', y=21, color=cols[6], lab='Summer offshore YOY')
  mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_OffYOY_Cond_Shelikof', y=22, color=cols[6], lab='Summer juvenile condition')
   mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_Juv_EuphDiet', y=23, color=cols[6], lab='Summer % euphausiid in juvenile diet')
   mycircles(survey='Ecosystem and Socioeconomic Profile', type='Sum_LCopepod_Shelikof', y=24, color=cols[6], lab='Summer large copepod')
        
  axis(1, at=seq(1970,2025, by=5))

  dev.off()
```



## AIC

```{r}

purrr::map_dfr(list(fit_assess_dsem_MS_iid,fit_assess_dsem_MS_AR1,
                    fit_assess_dsem_MS_regwind,fit_assess_dsem_MS_MapSpl,
                    fit_assess_dsem_MS_MapMod,fit_assess_dsem_MS_MapCpl),
               function(x){data.frame(name=x$version,npar=length(x$opt$par),
                                      nll=round(x$opt$objective,0),
                                      AIC=round(x$opt$AIC,0))})%>% 
  mutate(deltaAIC=AIC-min(AIC))
```

## sigma R

```{r}
purrr::map_dfr(list(fit_assess_dsem_MS_iid,
                    #fit_assess_dsem_MS_AR1, #don't have a simple way to get it for AR1 for now
                    fit_assess_dsem_MS_regwind,
                    fit_assess_dsem_MS_MapSpl,
                    fit_assess_dsem_MS_MapMod,fit_assess_dsem_MS_MapCpl),
       function(x){as_fitted_DAG_assessdsem(x,which.link = 'all',out.type = 'df') %>% 
                   select(name,Estimate) %>% mutate(model=x$version)}) %>% 
  filter(name=='sigmaR')



# as_fitted_DAG_assessdsem(fit_assess_dsem_MS_MapCpl,which.link = 'all',out.type = 'df')
```

